language: python
python:
  - "3.8"
# command to install dependencies
before_install:
  - "pip install -U pip"
  - "python setup.py install"
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest --cov-report term --cov=brainComputer tests/
after_success:
  # Upload coverage data to codecov
  - codecov
services:
  - mongodb
  - rabbitmq
